### ISSUE TITLE
Enable verbose build output (V=1)

### ISSUE THREAD

**Issue by craigbarnes** [exaexa/dte-debian#1]
I just noticed the Debian QA report at https://qa.debian.org/bls/packages/d/dte.html seems to be complaining about compiler flags being hidden from the log output (`compiler-flags-hidden`). The appropriate fix would be to export `V=1` in the environment.

Apparently the package is also [blocked](https://tracker.debian.org/pkg/dte) from migration into testing, but to my untrained eyes, it's hard to tell if this issue is the reason.

**Comment by exaexa** [comment]
Hello,

this seems a bit weird; compiler-flags-hidden doesn't seem like much of a problem but I'll fix the package asap. That issue is pretty common:
https://qa.debian.org/bls/bytag/W-compiler-flags-hidden.html

The actual excuse is here:
https://qa.debian.org/excuses.php?package=dte
...but that's already invalid because the build seems to have succeeded somewhere:
https://buildd.debian.org/status/package.php?p=dte
(apparently someone uploaded it manually).

I'll ask and let you know.

**Comment by craigbarnes** [comment]
> this seems a bit weird; compiler-flags-hidden doesn't seem like much of a problem but I'll fix the package

I guess it's so the log scanner can verify that the flags actually get passed to the compiler. It's quite common for non-generated makefiles to break this somehow, so I can understand why it's checked.

> ...but that's already invalid because the build seems to have succeeded somewhere:

The logs for the `arm64` build still seem to be missing from that page.

> I'll ask and let you know.

Cool, thanks.

By the way, it'd be awesome if the test suite could be run after building. Debian supports more architectures than pretty much any other distro and it'd be interesting to see if the tests pass on all of them.

**Comment by exaexa** [comment]
Seems there's a new policy about binary maintainer uploads that went effective for bullseye which we kindof hit; I will reupload the package with `V=1` fixed which should fix the whole thing.

**Comment by exaexa** [comment]
> test suite could be run

How do you run the tests? `make check` links some binary but it doesn't do anything for me.

**Comment by craigbarnes** [comment]
> How do you run the tests? make check links some binary but it doesn't do anything for me.

Yeah, it's just `make check`. I guess I should add some kind of visual confirmation that it's actually running.

**Comment by exaexa** [comment]
IIRC debian automatically runs make check, so probably the tests just passed. :]

**Comment by craigbarnes** [comment]
Ah yeah, you're right -- it is running. I just didn't see it in the logs the first time I looked.

**Comment by craigbarnes** [comment]
I guess I can close this now. I just release [v1.9](https://craigbarnes.gitlab.io/dte/releases.html) btw.
